### PR TITLE
big PR to enhance docker setup

### PR DESCRIPTION
**Pull request by BretFisher**
Sorry for a single big PR

- use multi-stage build to save 13MB on final image size
- change auth.sh to entrypoint script
- enhance entrypoint to look for either bind-mount of .sfdx, then envvar, then fail if neither exists
- add compose file for `docker-compose run sfdx` option

### CODE REVIEW

**Comment by wadewegner** [comment]
Thanks @BretFisher. Got a cheat sheet of all the commands you ran? 😁 If not, no worries -- I can review the recording.

**Comment by BretFisher** [comment]
added `.dockerignore`

**Comment by BretFisher** [comment]
ah man my mic was distorted on live stream.. macOS moved it to 100% :(

**Comment by wadewegner** [comment]
@BretFisher Sounds fine to me. Watching right now.

**Comment by BretFisher** [comment]
here's a shell history, a total mess but answers are in there somewhre :) https://d.pr/n/L1U2YY/oLi7vWLYzC

**Pull request merged**
